name: CI Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build_and_test:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4

    # -----------------------------------------------------
    # Setup Environment for Checks
    # -----------------------------------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Set up dependencies
      run: pip install -r dev-requirements.txt

    # -----------------------------------------------------
    # Linting
    # -----------------------------------------------------

    - name: Run Black formatter check
      run: black --check .

    - name: Run flake8 tests
      run: flake8 .

    - name: Run Bandit (SAST)
      run: bandit -r . -ll -x tests/

    - name: Run Safety CLI to check for vulnerabilities
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}

    # -----------------------------------------------------
    # Create Docker Image (Runs on all Branches)
    # -----------------------------------------------------
    - name: Setup Docker Builder
      uses: docker/setup-buildx-action@v3

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha

    - name: Build the Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        load: true
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
    
    # -----------------------------------------------------
    # Run Docker Image in Container (RUNS PYTEST UNIT TESTS)
    # -----------------------------------------------------
    - name: Run Pytest within the Docker Container
      env:
        ALL_TAGS: ${{ steps.meta.outputs.tags }}
      run: |
        TEST_TAG=$(echo "$ALL_TAGS" | head -n 1)

        docker run --rm -t $TEST_TAG \
          python -m pytest tests/unit \
          --cov=./app \
          --cov-report=xml:coverage.xml \
          --junitxml=pytest-report.xml
          


      